# Generated by Django 5.1.3 on 2024-11-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_question_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
